export const initialState = {
  levels: ["Beginner", "Intermediate", "Advanced"],
  languages: [
    "English",
    "Tiếng Việt",
    "Español",
    "Português",
    "日本語",
    "Deutsch",
    "Français",
    "Türkçe",
    "Italiano",
    "हिन्दी",
    "Polski",
    "Tamil",
    "मराठी",
    "Telugu",
    "Română",
  ],
  Categories: [],
  sections: [],
  lectures: [],
  quizes: [],
  quiz: {},
  assignments: [],
  lecture: null,
  quizResult: null,
  course: null,
  myCourse: [],
} as unknown as course;
