export const initialState = {
  isOpen: window.innerWidth >= 900,
  content: "",
  items: [],
  length: 0,
  orderId: "",
  setCourses: [],
  setNewestCourses: [],
  setCategory: [],
  listSections: [],
  listAccountApproved: [],
  courseDetail: {},
  AnalyticInsDashboard: {},
  popularInstructors: [],
  limitReviews: [],
  reviewSummary: {
    totalReviews: 0,
    averageRating: 0,
    ratingCounts: [0, 0, 0, 0, 0],
    ratingPercentages: [0, 0, 0, 0, 0],
  },
  filteredReviews: [],
  isReviewsLoading: false,
  users: [],
  courses: [],
  pendingCourses: [],
  monthlyUserCounts: [],
  revenueData: Array(12).fill(0),
  weeklyRevenueData: Array(7).fill(0),
  activeUsersCount: 0,
  totalReviewsCount: 0,
  pendingUsers: [],
  courseOfInstructor: [],
  courseOfPurchased: [],
  settingUser: {} as MODEL.USER,
  profileInstructer: {} as MODEL.USER,
  progressCourseOfUser: [],
  instructorCourse: [],
  instructorPurchase: [],
  instructorPendingCourse: [],
  setSubscribeChannels: [],
  completionRate: 0,
  averageProgress: 0,
  feedback: [],
  feedbackError: null,
} as globalType;
