version: '2.2'
services:
  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - /home/root/FE/dist:/usr/share/nginx/html
      - /home/root/FE/nginx.conf:/etc/nginx/conf.d/default.conf
